baseURL = 'https://www.yuanhao.site'
languageCode = 'zh-CN'
title = 'å¤šå¤´æ³¨æ„åŠ›'
theme = "PaperMod"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "archive"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/"

[[socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[socialIcons]]
name = "github"
url = "https://github.com/thuwyh"

[params]
subtitle = "AIç®—å‘½ æœ‹å…‹å…»ç”Ÿ"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
comments = true


  [params.assets]
  favicon = "/assets/favicon.ico"
  favicon16x16 = "/assets/favicon.ico"
  favicon32x32 = "/assets/favicon.ico"

  [params.homeInfoParams]
  Title = "Hi there ğŸ‘‹"
  Content = "æ¬¢è¿å…³æ³¨åŒåå…¬ä¼—å·ã€å¤šå¤´æ³¨æ„åŠ›ã€‘"

  [[params.socialIcons]]
  name = "kaggle"
  url = "https://www.kaggle.com/wuyhbb"

  [[params.socialIcons]]
  name = "zhihu"
  url = "https://www.zhihu.com/people/fjshwyh"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/thuwyh"

[services]
  [services.disqus]
    shortname = 'multihead-attention'
  [services.googleAnalytics]
    id = 'G-NWW8ZQMQ6Y'